version: '3.6'

# Replace each <mongo-user> with the desired username
# Replace each <mongo-pass> with the desired password
# Replace each <minio-ip-address> with the publicly available ip address or url without http(s)
# Replace <graphql-ip-address> with the publicly available ip address or url without http(s)

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    volumes:
      - ./data/data-mongo-cypress:/data/db
    ports:
      - 27017:27017
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: https://yettel-jenkins.eu.content-bloom.com:8081
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://admin:admin@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      GITLAB_JOB_RETRIES: 'false'
      MINIO_ACCESS_KEY: 'minioAdmin'
      MINIO_SECRET_KEY: 'minioPass'
      MINIO_ENDPOINT: 'https://yettel-jenkins.eu.content-bloom.com'
      MINIO_URL: 'https://yettel-jenkins.eu.content-bloom.com'
      MINIO_PORT: '8084'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress
      PROBE_LOGGER: "false"
    ports:
      - 7082:1234
      - 7083:1000
      - 7084:1010
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://admin:admin@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 7085:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: https://yettel-jenkins.eu.content-bloom.com:8085
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8081
      CI_URL: ''
    ports:
      - 7081:8081
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    network_mode: service:director
    environment:
      MINIO_ROOT_USER: '<minio-user>'
      MINIO_ROOT_PASSWORD: '<minio-pass>'
    volumes:
      - ./data/data-minio-cypress:/data
    command: minio server --console-address ":1010" /data

  createbuckets:
    image: minio/mc
    network_mode: service:director
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio https://yettel-jenkins.eu.content-bloom.com:8083 <minio-user> <minio-pass>;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc anonymous set download myminio/sorry-cypress;
      /usr/bin/mc anonymous set public myminio/sorry-cypress;
      exit 0;
      "
  e2e-electron:
    image: "cypress/included:12.11.0"
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
  e2e-chrome:
    image: "cypress/included:12.11.0"
    command: "--browser chrome"
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
  e2e-firefox:
    image: "cypress/included:12.11.0"
    command: "--browser firefox --config video=false"
    environment:
      - DEBUG=cypress:server:browsers:firefox-util,cypress:server:util:process_profiler
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
  e2e-edge:
    image: "cypress/included:12.11.0"
    command: "--browser edge"
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
