version: '3.6'

services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./data/data-mongo-cypress:/data/db

  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: https://yettel-jenkins.eu.content-bloom.com:8081
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/s3.driver'
      GITLAB_JOB_RETRIES: 'false'
      AWS_ACCESS_KEY_ID: 'key'
      AWS_SECRET_ACCESS_KEY: 'secret'
      S3_BUCKET: sorry-cypress
      PROBE_LOGGER: "false"
    ports:
      - 7082:1234
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 7085:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: https://yettel-jenkins.eu.content-bloom.com:8085
      GRAPHQL_CLIENT_CREDENTIALS: ''
      CI_URL: ''
      PORT: 8081
    ports:
      - 7081:8080
    depends_on:
      - mongo
      - api
